name: Employee-Churn-app

on: push

jobs:
  checking-app:
    name: employee-churn-app-testing-and-packaging
    runs-on: ubuntu-latest
    steps:
    - name: checkout-code
      uses: actions/checkout@v6

    - name: install python
      uses: actions/setup-python@v6
      with:
        python-version: 3.12.9

    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

    - name: install dependencies
      run: |
        pip install -r requirements.txt

    - name: test-api's 
      env:
        DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
      run: |
        python -m unittest testing/test_routes.py


    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

    - name: Login to ECR
      run: |
         aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 528043283929.dkr.ecr.ap-south-1.amazonaws.com

    - name: Build Docker Image
      if: success()
      run: |
          docker build -t churn-application-image:latest .

    - name: Tag Image
      run: |
          docker tag churn-application-image:latest 528043283929.dkr.ecr.ap-south-1.amazonaws.com/churn-application-image:latest

    - name: Push Image to ECR
      run: |
          docker push 528043283929.dkr.ecr.ap-south-1.amazonaws.com/churn-application-image:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}

        script: |
            aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 528043283929.dkr.ecr.ap-south-1.amazonaws.com
            docker push 528043283929.dkr.ecr.ap-south-1.amazonaws.com/churn-application-image:latest
            
            docker stop churn-app || true
            docker rm churn-app || true

            docker run -d -p 80:8000 \
            --restart unless-stopped \
            -e DAGSHUB_PAT=${{ secrets.DAGSHUB_PAT }} \
            --name churn-app \
            528043283929.dkr.ecr.ap-south-1.amazonaws.com/churn-application-image:latest

            docker logs churn-app --tail 50